### ISSUE TITLE
Add date added on the column to search the list much easier

### ISSUE THREAD

**Issue by karthiknish** [birobirobiro/awesome-shadcn-ui#133] opened 2024-10-16 13:06 UTC
If there is a new ui being added its hard to find on the current page

**Comment by avalynndev** [comment] 2024-10-18 14:28
duplicate of #55, and as shown birobirobiro as closed the issue indicating that he is probably not interested in added that feature or might have forgotten to add it.

**Closed** 2024-10-18 17:27 UTC
